### PR TITLE
Update Dependencies + Fix Chatroom Reply

### PR DESCRIPTION
**Pull request by tylerhammer**
Updated some base dependencies in order to no longer need a few packages that cause issues on compile. Allows us to run on Node 10.23.0 without issues. 

Fixed an issue where any response from a chatroom appeared as the chatroom instead of the user from the chatroom.

### CODE REVIEW

**Comment by rbrcurtis** [comment]
Hey @tylerhammer! I have no interest in maintaining this anymore; would you like me to transfer it to your github and give you the npm repo?

**Comment by tylerhammer** [comment]
That would work for me. Thanks!

**Comment by rbrcurtis** [comment]
Cool! What is your npmjs.org username?

**Comment by tylerhammer** [comment]
Its “tylerhammer” same as my GitHub username.

**Comment by rbrcurtis** [comment]
Ok, I gave you access to the npm package. You can just publish directly form your fork. Have fun!

**Pull request merged**
